modLoader = "javafml"
loaderVersion = "[4,)"
license = "Assets: All Rights Reserved; Code: LGPL-3.0"

[[mods]]
modId = "ancient_aether"
version = "0.11.0"
displayName = "Ancient Aether"
logoFile = "ancient_aether.png"
credits = "Contributors: TunefulTurnip, Zepalesque, rinOfTheStars | Translators: unroman, taizazanek, YuJianghan"
authors = "Builderdog"
description = "An exploration Aether Add-On that aims to overhaul the original ideas with modern takes."

[[dependencies.ancient_aether]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.72,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ancient_aether]]
modId = "aether"
type = "required"
versionRange = "[1.5.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ancient_aether]]
modId = "terrablender"
type = "required"
versionRange = "[1.0.3,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ancient_aether]]
modId = "aeroblender"
type = "required"
versionRange = "[1.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "ancient_aether.mixins.json"